// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPB-WPKNQM3mtA_LfrpQm2vrbzx3mG74c',
    appId: '1:616728188000:web:0cdb65bc3c149a1005df05',
    messagingSenderId: '616728188000',
    projectId: 'flutter-portfolio-dfe3e',
    authDomain: 'flutter-portfolio-dfe3e.firebaseapp.com',
    storageBucket: 'flutter-portfolio-dfe3e.appspot.com',
    measurementId: 'G-4ZDTQD328E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVnbZfRdJvkoGVQWUoK6RdSKuG0HTfNWY',
    appId: '1:616728188000:android:1f370465edc28ffa05df05',
    messagingSenderId: '616728188000',
    projectId: 'flutter-portfolio-dfe3e',
    storageBucket: 'flutter-portfolio-dfe3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg3Ckggjb3ebDRQswfwEXwHEOXFhs-s-8',
    appId: '1:616728188000:ios:434dbacf268c230705df05',
    messagingSenderId: '616728188000',
    projectId: 'flutter-portfolio-dfe3e',
    storageBucket: 'flutter-portfolio-dfe3e.appspot.com',
    iosBundleId: 'com.example.chabakeawChan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg3Ckggjb3ebDRQswfwEXwHEOXFhs-s-8',
    appId: '1:616728188000:ios:434dbacf268c230705df05',
    messagingSenderId: '616728188000',
    projectId: 'flutter-portfolio-dfe3e',
    storageBucket: 'flutter-portfolio-dfe3e.appspot.com',
    iosBundleId: 'com.example.chabakeawChan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPB-WPKNQM3mtA_LfrpQm2vrbzx3mG74c',
    appId: '1:616728188000:web:c4824fd85e9288d605df05',
    messagingSenderId: '616728188000',
    projectId: 'flutter-portfolio-dfe3e',
    authDomain: 'flutter-portfolio-dfe3e.firebaseapp.com',
    storageBucket: 'flutter-portfolio-dfe3e.appspot.com',
    measurementId: 'G-CRJY2ZQYT0',
  );
}
